name:        pubip
version:     0.6
summary:     Display public IPv6 or IPv4 address
confinement: strict
grade:       stable
icon:        misc/icon.svg
description: |
  To query IPv6 only use 'pubip -6'.
  To query IPv4 only use 'pubip -4'.
  The IP address is cached for 15 minutes.

apps:
  pubip:
    command: pubip
    plugs: [network]
  guiIPv4:
    command: echo "IPv4 -" $(pubip -4) | less -e
    plugs: [network]
  guiIPv6:
    command: echo "IPv6 -" $(pubip -6) | less -e
    plugs: [network]

parts:
  go:
    source-tag: go1.10
  pubip:
    after: [go]
    plugin: go
    source: .
    go-importpath: github.com/thibran/pubip_app
    organize:
      bin/pubip_app: bin/pubip

    install: |
      strip --strip-all $SNAPCRAFT_PART_INSTALL/bin/pubip_app