name: pubip
version: 0.3
summary:  Display public IPv6 or IPv4 IP address 
description: |
  To query for IPv6 only use 'pubip -6'.
  To query for IPv4 only use 'pubip -4'.
  Results are cached and reused if not older than 15 minutes.
confinement: strict
grade: stable

apps:
  pubip:
    command: bin/pubip_app.git
    plugs: [network]

parts:
  pubip:
    plugin: go
    source: https://github.com/thibran/pubip_app.git

