name: pubip
version: 0.5
icon: misc/icon.svg
summary:  Display public IPv6 or IPv4 address 
description: |
  To query IPv6 only use 'pubip -6'.
  To query IPv4 only use 'pubip -4'.
  The IP address is cached for 15 minutes.
confinement: strict
grade: stable

apps:
  pubip:
    command: pubip
    plugs: [network]
  guiIPv4:
    command: echo "IPv4 -" $(pubip -4) | less -e
    plugs: [network]
  guiIPv6:
    command: echo "IPv6 -" $(pubip -6) | less -e
    plugs: [network]

parts:
  pubip:
    plugin: go
    source: https://github.com/thibran/pubip_app.git
    organize:
      bin/pubip_app.git: bin/pubip