name: pubip
version: 0.2
summary: Display the public IPv4 or IPv6 IP address of this computer
description: Display the public IPv4 or IPv6 IP address of this computer
confinement: strict

apps:
  pubip:
    command: pubip_app
    plugs: [network]

parts:
  pubip:
    plugin: dump
    source: .
    
    filesets:
      binaries:
        - pubip_app
    stage:
      - $binaries
    snap:
      - $binaries
  # dig:
  #   plugin: nil
  #   stage-packages: [dnsutils]
  #   snap:
  #     - -etc
  #     - -lib
  #     - -usr/share
  #     - -usr/bin/host
  #     - -usr/bin/nslookup
  #     - -usr/bin/nsupdate
  #     - -usr/lib/gcc
  #     - -usr/lib/x86_64-linux-gnu/krb5
  #     - -usr/lib/x86_64-linux-gnu/openssl-1.0.0
  #     - -usr/lib/x86_64-linux-gnu/libkrb5.so*
  #     - -usr/lib/x86_64-linux-gnu/libkrb5support.so*
  #     - -usr/lib/x86_64-linux-gnu/libicui18n.so*
  #     - -usr/lib/x86_64-linux-gnu/libdns-pkcs11.so*
  #     - -usr/lib/x86_64-linux-gnu/libicuio.so*
  #     - -usr/lib/x86_64-linux-gnu/libicule.so*
  #     - -usr/lib/x86_64-linux-gnu/libiculx.so*
  #     - -usr/lib/x86_64-linux-gnu/libk5crypto.so*
  #     - -usr/lib/x86_64-linux-gnu/libgssapi_krb5.so*
  #     - -usr/lib/x86_64-linux-gnu/libicutest.so*
  #     - -usr/lib/x86_64-linux-gnu/libisc-pkcs11.so*
  #     - -usr/lib/x86_64-linux-gnu/libisccc.so*
  #     - -usr/lib/x86_64-linux-gnu/libicutu.so*

      # NEEDED
      # - -usr/lib/x86_64-linux-gnu/libicudata.so.57
      # - -usr/lib/x86_64-linux-gnu/libicudata.so.57.1
      # - -usr/lib/x86_64-linux-gnu/libicuuc.so.57
      # - -usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
      # - -usr/lib/x86_64-linux-gnu/libxml2.so.2
      # - -usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4
      # - -usr/lib/x86_64-linux-gnu/libGeoIP.so.1
      # - -usr/lib/x86_64-linux-gnu/libGeoIP.so.1.6.9
      # - -usr/lib/x86_64-linux-gnu/libdns.so.162
      # - -usr/lib/x86_64-linux-gnu/libdns.so.162.1.3
      # - -usr/lib/x86_64-linux-gnu/libbind9.so.140
      # - -usr/lib/x86_64-linux-gnu/libbind9.so.140.0.10
      # - -usr/lib/x86_64-linux-gnu/libisc.so.160
      # - -usr/lib/x86_64-linux-gnu/libisc.so.160.0.0
      # - -usr/lib/x86_64-linux-gnu/libisccfg.so.140
      # - -usr/lib/x86_64-linux-gnu/libisccfg.so.140.3.0
      # - -usr/lib/x86_64-linux-gnu/liblwres.so.141
      # - -usr/lib/x86_64-linux-gnu/liblwres.so.141.0.3

# TODO uncomment allfuncs.go code